### ISSUE TITLE
Issue with cucumber feature specs

### ISSUE THREAD

**Issue by StefanTegeltija** [bahmutov/cypress-split#20]
Hi Gled,

We have issue with feature specs.

Steps:
1. Add cucumber to your project: https://www.npmjs.com/package/cypress-cucumber-preprocessor
2. Open folder in e2e with the name features
3. Add feature file with the name for eg Header.feature and with the content

Feature: 001 Header
I want to check the header

Scenario: Header Logo
Given I navigate to 'https://www.google.com/'
Then Logo is visible

[
![Screenshot 2023-02-08 at 13 49 29](https://user-images.githubusercontent.com/26068374/217534876-fdbeb102-d6a6-4399-878b-25a80342effc.png)
![Screenshot 2023-02-08 at 13 50 06](https://user-images.githubusercontent.com/26068374/217534885-f798b005-1133-4c39-9ebe-808c62d423fa.png)
](url)

Run cypress-io/github-action@v5
/usr/local/bin/npm ci
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated gherkin@5.1.0: This package is now published under @cucumber/gherkin
npm WARN deprecated cucumber-expressions@6.6.2: This package is now published under @cucumber/cucumber-expressions
npm WARN deprecated cucumber-expressions@5.0.18: This package is now published under @cucumber/cucumber-expressions
npm WARN deprecated cucumber@4.2.1: Cucumber is publishing new releases under @cucumber/cucumber
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 785 packages, and audited 786 packages in 25s

94 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
/usr/local/bin/npx cypress cache list
┌─────────┬────────────┐
│ version │ last used  │
├─────────┼────────────┤
│ 12.5.1  │ 6 days ago │
└─────────┴────────────┘
/usr/local/bin/npx cypress verify

[STARTED] Task without title.
[SUCCESS] Task without title.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/cs-qa-automation/cs-qa-automation --files-from manifest.txt --use-compress-program zstdmt
Failed to save: Unable to reserve cache with key npm-linux-x64-0f1b354c96bd8ecc11cfcee398e6b15fcd0f5304981f726fd1d69f1bd0cfe453f56e601e3e99dd3813a1d288ca63355b901f0286ed4b57f7b924964afe1a3139, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/main, Key: npm-linux-x64-0f1b354c96bd8ecc11cfcee398e6b15fcd0f5304981f726fd1d69f1bd0cfe453f56e601e3e99dd3813a1d288ca63355b901f0286ed4b57f7b924964afe1a3139, Version: 04d00cc68e25ee34fd8b04095d0a46a28244d98af53e6925e47ed311d487b1d6
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/cs-qa-automation/cs-qa-automation --files-from manifest.txt --use-compress-program zstdmt
Failed to save: Unable to reserve cache with key cypress-linux-x64-0f1b354c96bd8ecc11cfcee398e6b15fcd0f5304981f726fd1d69f1bd0cfe453f56e601e3e99dd3813a1d288ca63355b901f0286ed4b57f7b924964afe1a3139, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/main, Key: cypress-linux-x64-0f1b354c96bd8ecc11cfcee398e6b15fcd0f5304981f726fd1d69f1bd0cfe453f56e601e3e99dd3813a1d288ca63355b901f0286ed4b57f7b924964afe1a3139, Version: 1955096f8dd018efdf62615d0a27779c95e9b0287a6a71bc182356f3b1a36196
[2123:0208/122921.036493:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Couldn't find tsconfig.json. tsconfig-paths will be skipped
cypress-split: there are 17 found specs
cypress-split: split 0 of 4
k  spec                                                         
-  -------------------------------------------------------------
1  cypress/e2e/features/00_Common/001_Header.feature            
2  cypress/e2e/features/00_Common/002_Footer.feature            
3  cypress/e2e/features/00_Common/003_Percy_Screenshots.feature 
4  cypress/e2e/features/02_Cookies_Policy/020_Cookie_Bar.feature
5  cypress/e2e/features/02_Cookies_Policy/021_Content.feature   

Your configFile threw an error from: /home/runner/work/cs-qa-automation/cs-qa-automation/cypress.config.js

The error was thrown while executing your e2e.setupNodeEvents() function:

Error: ENOENT: no such file or directory, open './undefined.json'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at setupNodeEvents (/home/runner/work/cs-qa-automation/cs-qa-automation/cypress.config.js:16:20)
    at /home/runner/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:118:[14](https://github.com/casinogrounds/cs-qa-automation/actions/runs/4124094420/jobs/7122931617#step:4:15)
    at tryCatcher (/home/runner/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/runner/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/method.js:39:29)
    at RunPlugins.load (/home/runner/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:1[15](https://github.com/casinogrounds/cs-qa-automation/actions/runs/4124094420/jobs/7122931617#step:4:16):9)
    at RunPlugins.runSetupNodeEvents (/home/runner/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:276:10)
    at EventEmitter.<anonymous> (/home/runner/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:[18](https://github.com/casinogrounds/cs-qa-automation/actions/runs/4124094420/jobs/7122931617#step:4:19)5:22)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at process.<anonymous> (/home/runner/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:527:28)
    at process.emit (node:domain:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/home/runner/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:[21](https://github.com/casinogrounds/cs-qa-automation/actions/runs/4124094420/jobs/7122931617#step:4:22))
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results

**Comment by bahmutov** [comment]
Could you make a tiny repo with those steps already done so I can simply grab it and see the problem?Sent from my iPhoneOn Feb 8, 2023, at 07:53, Stefan Tegeltija ***@***.***> wrote:﻿
Hi Gled,
I think that we have issue with feature specs.
Steps:

Add cucumber to your project: https://www.npmjs.com/package/cypress-cucumber-preprocessor
Open folder in e2e with the name features
Add feature file with the name for eg Header.feature and with the content

Feature: 001 Header
I want to check the header
Scenario: Header Logo
Given I navigate to 'https://www.google.com/'
Then Logo is visible

**Comment by bahmutov** [comment]
For me it works straight out of the box, see https://github.com/bahmutov/cypress-split-cucumber-example
