### ISSUE TITLE
Error: File '../../tsconfig.base' not found

### ISSUE THREAD

**Issue by sevilyilmaz** [bahmutov/cypress-split#271]
I started getting this error after bumping the version from `1.18.5` to `1.23.0`.  It seems like it's coming from `find-cypress-specs` but I couldn't pinpoint it.

```
Error: File '../../tsconfig.base' not found.
    at je (/builds/node_modules/get-tsconfig/dist/index.cjs:3:9102)
    at te (/builds/node_modules/get-tsconfig/dist/index.cjs:3:10066)
    at ie (/builds/node_modules/get-tsconfig/dist/index.cjs:3:10781)
    at Object.$e [as getTsconfig] (/builds/node_modules/get-tsconfig/dist/index.cjs:3:10886)
    at Object.<anonymous> (/builds/node_modules/tsx/dist/cjs/index.cjs:1:726)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/builds/node_modules/find-cypress-specs/src/index.js:19:1)
    at Module._compile (node:internal/modules/cjs/loader:[125](https://xxx/-/jobs/203594291#L125)4:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/builds/node_modules/cypress-split/src/parse-inputs.js:4:22)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:[130](https://xxx/-/jobs/203594291#L130)8:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
```

**Comment by bahmutov** [comment]
Could you try different versions between 1.18 and 1.23 to locate the breaking version?Sent from my iPhoneOn Apr 19, 2024, at 10:32, Sevil Yılmaz ***@***.***> wrote:﻿
I started getting this error after bumping the version from 1.18.5 to 1.23.0.  It seems like it's coming from find-cypress-specs but I couldn't pinpoint it.
Error: File '../../tsconfig.base' not found.
    at je (/builds/node_modules/get-tsconfig/dist/index.cjs:3:9102)
    at te (/builds/node_modules/get-tsconfig/dist/index.cjs:3:10066)
    at ie (/builds/node_modules/get-tsconfig/dist/index.cjs:3:10781)
    at Object.$e [as getTsconfig] (/builds/node_modules/get-tsconfig/dist/index.cjs:3:10886)
    at Object.<anonymous> (/builds/node_modules/tsx/dist/cjs/index.cjs:1:726)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/builds/node_modules/find-cypress-specs/src/index.js:19:1)
    at Module._compile (node:internal/modules/cjs/loader:[125](https://xxx/-/jobs/203594291#L125)4:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/builds/node_modules/cypress-split/src/parse-inputs.js:4:22)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:[130](https://xxx/-/jobs/203594291#L130)8:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)

**Comment by sevilyilmaz** [comment]
That doesn't give any other information as the command fails on [L19](https://github.com/bahmutov/find-cypress-specs/blob/main/src/index.js#L19) in find-cypress-specs where `tsx` [introduced as a replacement](https://github.com/bahmutov/find-cypress-specs/commit/1e669c9cb2545b6cc9cc3ca907490012af1dae12#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R19) of `ts-node`. 

`tsx` uses `get-tsconfig` to find tsconfig files which seems couldn't find the base config where we add it to out tsconfig files as extension like this:

```json
{
  "extends": "../../tsconfig.base",
}
```
