### ISSUE TITLE
Cypress run stopped working in Github Actions. Threw TypeError: patterns.reduce is not a function error under cypress-split

### ISSUE THREAD

**Issue by fatinfarzanaazizan** [bahmutov/cypress-split#78]
Hi, thank you so much for creating cypress-split. It's a very helpful tool.

It seems that a few days ago, my cypress job runs in Github Actions are failing with the error below. No changes were done from my side. I've tried increasing cypress version and such but no luck. Could you help to determine what might've caused this issue? I've also included my cypress.config.js file below for reference. thank you.

```
The error was thrown while executing your e2e.setupNodeEvents() function:

TypeError: patterns.reduce is not a function
    at Object.expandPatternsWithBraceExpansion (/home/runner/work/AutomationCypress/node_modules/fast-glob/out/utils/pattern.js:131:21)
    at processPatterns (/home/runner/work/AutomationCypress/node_modules/fast-glob/out/managers/tasks.js:27:34)
    at Object.generate (/home/runner/work/AutomationCypress/node_modules/fast-glob/out/managers/tasks.js:7:20)
    at getWorks (/home/runner/work/AutomationCypress/node_modules/fast-glob/out/index.js:91:31)
    at AsyncFunction.sync (/home/runner/work/AutomationCypress/node_modules/fast-glob/out/index.js:23:23)
    at AsyncFunction.module.exports.sync (/home/runner/work/AutomationCypress/node_modules/globby/index.js:151:42)
    at findCypressSpecsV10 (/home/runner/work/AutomationCypress/node_modules/find-cypress-specs/src/index.js:150:24)
    at findCypressSpecs (/home/runner/work/AutomationCypress/node_modules/find-cypress-specs/src/index.js:233:21)
    at getSpecs (/home/runner/work/AutomationCypress/node_modules/find-cypress-specs/src/index.js:210:10)
    at cypressSplit (/home/runner/work/AutomationCypress/node_modules/cypress-split/src/index.js:94:15)
    at setupNodeEvents (/home/runner/work/AutomationCypress/cypress.config.js:11:3)
```

cypress.config.js file:
```
const { defineConfig } = require("cypress")
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor")
const cucumberPreprocessor = require("@badeball/cypress-cucumber-preprocessor")
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild")
const cypressSplit = require('cypress-split')

async function setupNodeEvents(cypressOn, config) {
  const on = require('cypress-on-fix')(cypressOn)
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await cucumberPreprocessor.addCucumberPreprocessorPlugin(on, config)
  cypressSplit(on, config)

  on(
    "file:preprocessor", 
      createBundler({
        plugins: [createEsbuildPlugin.default(config)],
      })
  );

  on('task', {
    log(message) {
      console.log(message)
      return null
    }
  })

  // Make sure to return the config object as it might have been modified by the plugin.
  return config
}

module.exports = defineConfig({
  e2e: {
    specPattern: "**/*.feature",
    supportFile: false,
    setupNodeEvents,
    experimentalSessionAndOrigin: true,
    chromeWebSecurity: false
    },
});
```

version:
"cypress-split": "^1.3.12"
"cypress": "^11.2.0"

related github actions versions:
cypress-io/github-action@v5
runs-on: ubuntu-22.04

**Comment by bahmutov** [comment]
Hello,
Can you try using exact version of this plugin and go back to find the last working version https://github.com/bahmutov/cypress-split/releases ?
Also, for the breaking version, can you provide the DEBUG logs? https://github.com/bahmutov/cypress-split#debugging

**Comment by fatinfarzanaazizan** [comment]
Hi @bahmutov, thanks for your reply. The version that used to work (11.2) is the same as the version that's failing. It started failing on github actions 5 days ago.

Attached the debug logs for reference
[Cypress-11.2-debug-log-githubactions.txt](https://github.com/bahmutov/cypress-split/files/11963884/Cypress-11.2-debug-log-githubactions.txt)

Let me know if you require more info. Thank you

**Comment by tamasmagyar** [comment]
Error might be coming from fast-glob? https://github.com/mrmlnc/fast-glob/issues/404

**Comment by toriumi0118** [comment]
try adding

`excludeSpecPattern: ["*.hot-update.js"]`

to your cypress.config.js file. like below

```
module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      cypressSplit(on, config);
      // IMPORTANT: return the config object
      return config;
    },
    excludeSpecPattern: ["*.hot-update.js"],
  },
});
```

the rest of configurations is depends on your setting.

**Comment by bahmutov** [comment]
Updated the code to fix. Soon will be released.

**Comment by fatinfarzanaazizan** [comment]
Thanks @bahmutov! Fix is working well :)
